### ISSUE TITLE
SP manifest boot order parsing error

### ISSUE THREAD

**Issue by odeprez** [ARM-software/ff-a-acs#4]
Hi,

FF-A ACS test suite fails with TF-A/Hafnium master as SP manifests use non-unique boot order fields

https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp1.dts#L26
https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp2.dts#L26
https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp3.dts#L26

See the job run:
https://ci.trustedfirmware.org/view/Hafnium/job/hafnium-acs-test/3/

And log:
https://ci-builds.trustedfirmware.org/static-files/JYBElETTRWsV383EMsIavxnUhSxD2gwjoDTXeqXSAJgxNjg5NTg2NzA2ODUxOjc6b2RlcHJlejp2aWV3L0hhZm5pdW0vam9iL2hhZm5pdW0tYWNzLXRlc3QvMy9hcnRpZmFjdA==/logs/fvp-uart0.log

_ERROR: Boot order must be a unique value.
ERROR: Error parsing partition manifest: Boot order should be a unique value less than default largest value.
Panic: Could not parse manifest: Boot order should be a unique value less than default largest value._

**Comment by jk-arm** [comment]
@odeprez sure we will have a look at it, @mahesh-bireddy please have a look at it

**Comment by mahesh-bireddy** [comment]
Fixed SP manifest boot order issue.
https://github.com/ARM-software/ff-a-acs/commit/e97ef540ab89517d64db30b63de420919394bf11
