### ISSUE TITLE
Invalid FFA_SECONDARY_EP_REGISTER SMC function id

### ISSUE THREAD

**Issue by odeprez** [ARM-software/ff-a-acs#5]
FFA_SECONDARY_EP_REGISTER function id is x4000087

https://github.com/ARM-software/ff-a-acs/blob/main/val/inc/val_ffa.h#L58
https://github.com/ARM-software/ff-a-acs/blob/main/val/inc/val_ffa.h#L78

**Comment by mahesh-bireddy** [comment]
Fixed FFA_SECONDARY_EP_REGISTER function id.
https://github.com/ARM-software/ff-a-acs/commit/029782663adc01e9eeed19aa74e35454ea737b42
