### ISSUE TITLE
SP1 accesses non-secure devices and memory

### ISSUE THREAD

**Issue by odeprez** [ARM-software/ff-a-acs#6]
SP1 accesses non-secure device and memory resources leading to S2 page faults.

The following devices are non-secure in the FVP platform:
https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp1.dts#L37
https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp1.dts#L49

Is this desired a secure partition controls a non-secure uart and ns watchdog?

Despite secure resources shall be favoured when accessed from a SP,
at a minimum the device attributes should be NS/read/write (0xb) rather than read/write (0x3).

The NVM region is normal DRAM:
https://github.com/ARM-software/ff-a-acs/blob/main/platform/manifest/tgt_tfa_fvp/sp1.dts#L43
Should it better be declared in a memory-region node?
Similarly to device regions above attributes shall be NS/read/write.

See the failing jenkins job log
https://ci-builds.trustedfirmware.org/static-files/3PeJ4FMowjteWZosU5RLhvaxsc84fvSsWT8aheSAgAExNjkzOTA2Mjk0MTQyOjc6b2RlcHJlejp2aWV3L0hhZm5pdW0vam9iL2hhZm5pdW0tYWNzLXRlc3QvNS9hcnRpZmFjdA==/logs/fvp-uart0.log

**Comment by odeprez** [comment]
A suggested change to unblock things

diff --git a/platform/manifest/tgt_tfa_fvp/sp1.dts b/platform/manifest/tgt_tfa_fvp/sp1.dts
index 81d7fb3..fda21c9 100644
--- a/platform/manifest/tgt_tfa_fvp/sp1.dts
+++ b/platform/manifest/tgt_tfa_fvp/sp1.dts
@@ -37,19 +37,19 @@
         uart2 {
             base-address = <0x1c0b0000>;
             pages-count = <16>;
-            attributes = <0x3>; /* read-write */
+            attributes = <0xb>; /* NS-read-write */
         };
 
         nvm {
             base-address = <0x00000000 0x82800000>;
             pages-count = <64>;
-            attributes = <0x3>; /* read-write */
+            attributes = <0xb>; /* NS-read-write */
         };
 
         watchdog {
             base-address = <0x00000000 0x1C0F0000>;
             pages-count = <64>;
-            attributes = <0x3>; /* read-write */
+            attributes = <0xb>; /* NS-read-write */
         };
 
         sec_twdog {

**Comment by mahesh-bireddy** [comment]
Hi Olivier,
Thanks for the patch.

Currently, we are accessing non-secure regions in some tests.
Merged the patch: https://github.com/ARM-software/ff-a-acs/commit/0d123a18a9b7c54bafebe72eb5566d6bc1a366b2
